version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: folio-dev
    ports:
      - '3000:3000'
    command: yarn dev
    env_file:
      - .env  
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json