import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider, SignInButton, UserButton, currentUser } from "@clerk/nextjs";



const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const user = await currentUser();
  return (
    <ClerkProvider>
      <html lang="en">
          <head>
            <title>folio</title>
          </head>
          <body className={`font-sans ${inter.variable} min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white`}>
            <div className="flex container bg-white/10 mx-auto rounded-full items-center">
              <div className="justify-center w-15 h-15 p-3">
                <UserButton />
              </div>
              {!user && <div className="rounded-full bg-white/10 px-5 py-3 font-semibold transition hover:bg-white/20 h-10">
                <span className="align-top md:align-top">
                  <SignInButton />
                </span>
              </div>}
            </div>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </body>
      </html>
    </ClerkProvider>
  );
}
