name: basic tests
run-name: test
on:
  push:
    branches:
      - main
jobs:
  Simple-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Using Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
      
      - name: Install dependencies
        run: yarn install

      - name: Lint files
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ CLERK_SECRET_KEY }} 
          NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
          NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
          NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: /
          NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: /
        run: yarn lint
